[workspace]
members = ["apollo-federation-types", "apollo-composition"]
resolver = "2"

[workspace.dependencies]
apollo-compiler = "1.32.0"

# pinning to a revision latest dev revision
apollo-federation = { git = "https://github.com/apollographql/router", rev = "82aef5f3bdcdabb913c0cbe53ac7b6b16df60883" }
